version: 2.1 # CircleCIのコンフィグファイルのバージョン
      
jobs: # ジョブの定義
  my1stjob: # ジョブ名
    docker: # 使用するDockerイメージの指定
      - image: cimg/node:14.13.0 # Node.jsがプリンターされたDockerイメージを指定
    steps: # ジョブ内で実行するステップの定義
      - checkout # リポジトリのソースコードをチェックアウト
      - run: # コマンド実行①
          name: echo hello world # ステップ名（CircleCIの画面に表示される）
          command: echo "hello world" # 「hello world」を出力
      - run: # コマンド実行②
          name: Install dependencies # ステップ名（CircleCIの画面に表示される）
          command: npm install  # npm install コマンドで依存関係をインストール
      - run: # コマンド実行③
          name: Run Tests # ステップ名（CircleCIの画面に表示される）
          command: npm run test # 「npm run test」コマンドでテストを実行

workflows: # ワークフローの定義
  my-1st-workflow: # ワークフロー名
    jobs: # ワークフロー内で実行するジョブ
      - my1stjob # jobsで定義された「my1stjob」を実行
